[logger]
# Default logging level for Streamlit and app logs
level = "info"

[server]
# Helpful during development; reloads on save
runOnSave = true

[client]
# Show developer-oriented toolbar options
toolbarMode = "developer"
